In [58]:
torch.cat((x,x))

tensor([[-0.1584],
        [-0.1584]])

In [145]:
class functionc(nn.Module):
    def __init__(self):
        super(functionc,self).__init__()
        self.layer1 = nn.Linear(1,1) # ax + bx +c
    
    def forward(self,x):
        # x_c = self.layer1(x)
        # y =  x_c
        # x = torch.cat((x**2,x))
        # x = torch.cat((x,x))
        y = self.layer1(x)
        return y

x = torch.randn(1)
model = functionc()

print(y.shape,model)

torch.Size([200]) functionc(
  (layer1): Linear(in_features=1, out_features=1, bias=True)
)


In [146]:
epochs = 10

x = torch.randn(100)

y_noise = torch.rand_like(x)/10000
y = x**2 + y_noise#+x -1


optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
loss_function = nn.CrossEntropyLoss()

losses = []
optimizer = optim.SGD(model.parameters(), lr=0.001)


for epoch in range(epochs):
    total_loss = 0
    for t,l in zip(x,y):
        t = t.view(1)
        print(t.shape,t)
        break
    break

torch.Size([1]) tensor([0.6823])


In [147]:
epochs = 100

x = torch.randn(100)

y_noise = torch.rand_like(x)/10000
y = x**2 + y_noise#+x -1
bias = torch.ones(100)*3
y = torch.cat((3*x,bias))

# optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
# loss_function = nn.CrossEntropyLoss()

optimizer = optim.SGD(model.parameters(), lr=0.001)
loss_function = nn.MSELoss()
losses = []


for epoch in range(epochs):
    total_loss = 0
    for t,l in zip(x,y):
        t = t.view(1)
        model.zero_grad()
        model = functionc()
        predict = model(t)

        loss = loss_function(l,predict)

        
        loss.backward()
        optimizer.step()

        # Get the Python number from a 1-element Tensor by calling tensor.item()
        total_loss += loss.item()
    losses.append(total_loss)
    print(total_loss)

920.1608974221854
980.2761790134246
1045.310549227026
948.3748958832584
1039.349765284278
1002.3099746222142
915.3746150353909
935.433474558231
852.0179939940572
1097.1686988009023
1043.2719027301791
913.345213494089
974.9892131341621
947.640390174929
1015.1925799928431
1013.9833407964943
980.7965435747756
948.4851291103987
1032.8969557851087
856.6052803936655
946.274758366779
1039.6189722664271
1022.386949970678
1045.3034228477627
911.8505708009616
1004.9154563595148
842.0430841203779
811.4580070205411
1092.2538089914015
1122.4621111992747
937.7072121411329
1005.0165671943687
923.8061344405869
1051.5202538906597
960.3818247611634
1068.6863475466962
972.2051185765376
1072.3302074262756
969.162431496894
906.7463070202866
857.4494433498476
908.9588814821134
1012.9018832739821
1099.6797491281322
998.8154086148425
1034.2913516986591
1096.5558506937232
898.2441438496535
1122.5605855985182
1135.2816524750087
1008.1899939845316
1039.334515693714
1006.3104268109892
890.1612941946369
1015.65062

In [44]:
# a*x**2 + b*x**1 + c


functionc(
  (layer1): Linear(in_features=1, out_features=2, bias=True)
)

In [148]:
model.layer1.weight , model.layer1.bias

(Parameter containing:
 tensor([[0.4440]], requires_grad=True),
 Parameter containing:
 tensor([0.5884], requires_grad=True))

In [149]:

x = torch.tensor([2.])
model = functionc()
model(x)

tensor([1.4094], grad_fn=<AddBackward0>)

# regression model


In [ ]:
def model(nn.Module):
    def __init__(self):
        self.layer1 = nn.Linear(
            
        )

In [185]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [199]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
y_train = torch.FloatTensor([[5], [7], [9]])
# y_train = torch.FloatTensor([[5], [17], [37]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = Model()

optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs,model.linear.weight.item(),model.linear.bias.item(), cost.item()
        ))


Epoch    0/1999 W: 0.509, b: -0.114 Cost: 48.731510
Epoch  100/1999 W: 2.712, b: 1.381 Cost: 0.377661
Epoch  200/1999 W: 2.560, b: 1.728 Cost: 0.233371
Epoch  300/1999 W: 2.440, b: 2.000 Cost: 0.144209
Epoch  400/1999 W: 2.346, b: 2.214 Cost: 0.089113
Epoch  500/1999 W: 2.272, b: 2.382 Cost: 0.055066
Epoch  600/1999 W: 2.214, b: 2.514 Cost: 0.034028
Epoch  700/1999 W: 2.168, b: 2.618 Cost: 0.021027
Epoch  800/1999 W: 2.132, b: 2.700 Cost: 0.012993
Epoch  900/1999 W: 2.104, b: 2.764 Cost: 0.008029
Epoch 1000/1999 W: 2.082, b: 2.814 Cost: 0.004961
Epoch 1100/1999 W: 2.064, b: 2.854 Cost: 0.003066
Epoch 1200/1999 W: 2.050, b: 2.885 Cost: 0.001895
Epoch 1300/1999 W: 2.040, b: 2.910 Cost: 0.001171
Epoch 1400/1999 W: 2.031, b: 2.929 Cost: 0.000723
Epoch 1500/1999 W: 2.024, b: 2.944 Cost: 0.000447
Epoch 1600/1999 W: 2.019, b: 2.956 Cost: 0.000276
Epoch 1700/1999 W: 2.015, b: 2.966 Cost: 0.000171
Epoch 1800/1999 W: 2.012, b: 2.973 Cost: 0.000105
Epoch 1900/1999 W: 2.009, b: 2.979 Cost: 0.00006

In [197]:
x = torch.tensor([4.])
model(x)

tensor([51.5665], grad_fn=<AddBackward0>)