In [27]:
import torch
i/gE3skAc9aCAU
# make tensor
torch.manual_seed(1004)
print(torch.rand(2,2)) # 0~1 R
print(torch.randn(2,2)) # normal distribution X ~ N(0,1) 
print(torch.randint(low=1,high=3,size=(2,2))) # low ~ high Intger

# imitate input
input = torch.tensor([[1,2],[3,4]])
input = torch.randn(3,3)
print(torch.rand_like(input)) # same shape as input. 0~1 R
print(torch.randn_like(input)) 
print(torch.randint_like(input,-2,5))

tensor([[0.9716, 0.3893],
        [0.2629, 0.9071]])
tensor([[ 0.4394, -0.7688],
        [ 1.0868, -1.5346]])
tensor([[2, 2],
        [1, 1]])
tensor([[0.5851, 0.0048, 0.2220],
        [0.9200, 0.0642, 0.0846],
        [0.6534, 0.0869, 0.8667]])
tensor([[-0.2142,  0.4358,  0.9602],
        [ 0.6255, -0.5357, -1.2964],
        [-0.0624,  1.2123,  2.2158]])
tensor([[ 0.,  4., -2.],
        [ 4., -1.,  0.],
        [ 1.,  1.,  1.]])
