In [91]:
# custom loss
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset,DataLoader,TensorDataset
from transformers import AdamW


def my_loss(output, target):
    loss = torch.mean((output - target)**2)
    return loss

def my_cross_entropy(x, y):
    log_prob = -1.0 * F.log_softmax(x, 1)
    loss = log_prob.gather(1, y.unsqueeze(1))
    loss = loss.mean()
    return loss


In [98]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset,DataLoader,TensorDataset
from transformers import AdamW

LEARNING_RATE = 0.2
NUM_EPOCHS = 100
BATCH_SIZE = 64

# data
x = torch.randn(1,3,224,224 )
# x = torch.randn(1,2)
X = torch.randn(0)
for _ in range(BATCH_SIZE*4):
    X = torch.concat((X,x),dim=0)
    
y = torch.randn(1, 77)
# y = torch.randn(1, 2)
Y = torch.randn(0)
for _ in range(BATCH_SIZE*4):
    Y = torch.concat((Y,y),dim=0)

print(X.shape,Y.shape)
# X = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
# Y = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)**2
dataset = TensorDataset(X, Y)

My_DataLoader = DataLoader(dataset,
                        batch_size=BATCH_SIZE, 
                        shuffle=False
                        )

torch.Size([256, 3, 224, 224]) torch.Size([256, 77])


In [103]:
model = nn.Sequential(
    nn.Linear(3*224*224,2),
    nn.Tanh(),
)

model2 = nn.Sequential(
    nn.Linear(77,2),
    nn.Tanh()
)

# optimizer
optimizer = optim.SGD(model.parameters(),lr=LEARNING_RATE)
optimizer2 = optim.SGD(model2.parameters(),lr=LEARNING_RATE)
# optimizer = AdamW(model.parameters(), lr=1e-1)

# loss
criterion = nn.MSELoss()
criterion = nn.CrossEntropyLoss()
criterion = my_loss
# criterion = my_cross_entropy


model.train()
for epoch in range(NUM_EPOCHS):
    for x,y in My_DataLoader:
        optimizer.zero_grad()
        x = x.view(BATCH_SIZE,-1)
        # y = y.view(BATCH_SIZE,-1)
        
        y_pred = model(x)
        z_pred = model2(y)
        loss = criterion(z_pred, y_pred)

        loss.backward()
        optimizer.step()
        
# print(model.weight.grad)

# print(model.weight)

print('prediction')
print(y_pred[0])
print()
print('true value')
print(z_pred[0])

prediction
tensor([-1.,  1.], grad_fn=<SelectBackward0>)

true value
tensor([-0.1126,  0.0125], grad_fn=<SelectBackward0>)


In [105]:
# loss값이 얼마나 차이나는지 확인.

def my_cross_entropy(x, y):
    log_prob = -1.0 * F.log_softmax(x, 1)
    loss = log_prob.gather(1, y.unsqueeze(1))
    loss = loss.mean()
    return loss

criterion = nn.CrossEntropyLoss()

batch_size = 5
nb_classes = 10
x = torch.randn(batch_size, nb_classes, requires_grad=True)
y = torch.randint(0, nb_classes, (batch_size,))

loss_reference = criterion(x, y)
loss = my_cross_entropy(x, y)

print(loss_reference - loss)

tensor(0., grad_fn=<SubBackward0>)


In [122]:
# from transformers import CLIPProcessor, CLIPModel,AutoProcessor, AutoTokenizer

# processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")
# tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")
# model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

# REPO_NAME = "clip"

# model.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )

# tokenizer.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )

# processor.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )

In [129]:
import argparse 

parser = argparse.ArgumentParser()
parser.add_argument(dest="width", action="store")
parser.add_argument(dest="height", action="store")
parser.add_argument("--frames", dest="frames", action="store")
parser.add_argument("--qp", dest="qp", action="store")
parser.add_argument("--configure", dest="configure", action="store")

args = parser.parse_args(["64", "56", "--frames", "60", "--qp", "1", "--configure", "AI"])
print(args.width, args.height, args.frames, args.qp, args.configure)

64 56 60 1 AI


In [133]:
import argparse

parser = argparse.ArgumentParser()

# 데이터 세트
# parser.add_argument("--data_dir", type=str, required=True, help="데이터 세트 디렉토리")
# parser.add_argument("--image_list_file", type=str, required=True, help="이미지 목록 파일")
# parser.add_argument("--text_list_file", type=str, required=True, help="텍스트 목록 파일")

# 모델
# parser.add_argument("--model_type", type=str, required=True, help="모델 유형")
# parser.add_argument("--model_name_or_path", type=str, required=True, help="모델 이름 또는 경로")

# 학습
parser.add_argument("--batch_size", type=int, default=128, help="배치 크기")
# parser.add_argument("--epochs", type=int, default=10, help="에폭 수")
# parser.add_argument("--learning_rate", type=float, default=1e-4, help="학습률")

# 기타
# parser.add_argument("--log_dir", type=str, default="./logs", help="로그 디렉토리")
# parser.add_argument("--seed", type=int, default=42, help="시드")
# 
args = parser.parse_args([64,15,1e-5,77])
args = parser.parse_args(["--batch_size",64])





TypeError: 'int' object is not subscriptable

In [27]:
a = torch.tensor([-1])
torch.log(a)

tensor([nan])

In [28]:
import torch 
import torch.nn.functional as F
batch_size=64
h1 = torch.randn(batch_size,512)
cosine_sim = F.cosine_similarity(h1,h1)
alignment = -torch.exp(cosine_sim)


tensor([-2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183,
        -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183, -2.7183])

In [ ]:


image_embeddings1 = y1.image_embeds
text_embeddings2 = y1.text_embeds

image_embeddings2 = y2.image_embeds
text_embeddings2 = y2.text_embeds

# cosine
# alignment_ii = -torch.log(F.cosine_similarity(image_embeddings,image_embeddings2))
h1 = torch.randn(batch_size,512)
alignment_it1 = -(tau*F.cosine_similarity(image_embeddings,text_embeddings))
alignment_it2 = -(tau*F.cosine_similarity(image_embeddings2,text_embeddings2))

# batch_size로 나눠주기. normalize는 어떻게 해주지?
alignment_it1 = alignment_it1/batch_size
alignment_it2 = alignment_it2/batch_size

alignment_it1.to(device)
alignment_it2.to(device)
anisotropy = torch.empty_like(alignment_it1)

for i in range(batch_size):
    I1 = image_embeddings[i]
    I2 = image_embeddings2[i]
    T1 = text_embeddings[i]
    T2 = text_embeddings2[i]
    anisotropyj = 0
    for j in range(batch_size): 
        if i!=j:
            anisotropyj+= F.cosine_similarity(image_embeddings2[i,:],text_embeddings2[j,:],dim=0)
            anisotropyj+= F.cosine_similarity(image_embeddings[i,:],text_embeddings[j,:],dim=0)
    # tau 값을 넣으면 너무 커져서 안됨 .. batch size에 따라서 조절해야할듯..        
    anisotropy[i] = anisotropyj/batch_size#*tau
anisotropy.to(device)            

# loss function
total_loss = torch.sum(alignment_it1+alignment_it2+anisotropy)/batch_size


In [107]:
torch.sum(h1+h1)

tensor(132.7580)

In [33]:
from abc import ABC
from abc import abstractmethod
# static method
class Loss(ABC):
    # @abstractmethod
    # def __init__(self) -> None:
        # super().__init__()
        
    @abstractmethod
    def Alignment(self) -> None:
        """Define layers in ther model."""
        raise NotImplementedError
    
    @abstractmethod
    def Anisotropy(self) -> None:
        """Define layers in ther model."""
        raise NotImplementedError

In [81]:
x = torch.tensor([[1,2,0,0,1],[1,1,1,1,1]],dtype=torch.float)
y = torch.tensor([[0,0,-1,0,-1],[1,1,1,1,1]],dtype=torch.float)

F.cosine_similarity(x[1,:],y[0,:],dim=0)

tensor(-0.6325)

In [85]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
output = F.cosine_similarity(input1, input2,dim=0)
print(output.shape)

torch.Size([128])


In [114]:
import torch
import torch.nn.functional as F

class SimLoss(Loss): # what i want to similar
    def __init__(self,hi1:torch.tensor
                ,ht1:torch.tensor
                ,hi2:torch.tensor
                ,ht2:torch.tensor
                ):
        self.hi1 = hi1
        self.ht1 = ht1
        self.hi2 = hi2
        self.ht2 = ht2
        self.tau = 1/0.05
        self.batch_size = batch_size
        
    def Alignment(self):
        Ali1 = -(self.tau*F.cosine_similarity(self.hi1,self.ht1))
        Ali2 = -(self.tau*F.cosine_similarity(self.hi2,self.ht2))
        return (Ali1+Ali2)/self.batch_size
    
    def Anisotropy(self):
        anisotropy = torch.empty(batch_size)
        for i in range(batch_size):
            I1 = self.hi1[i]
            I2 = self.hi2[i]
            anisotropyj = 0
            for j in range(batch_size):
                if i!=j:
                    T1 = self.ht1[j]
                    T2 = self.ht2[j] 
                    anisotropyj+=F.cosine_similarity(I1,T1,dim=0)
                    anisotropyj+=F.cosine_similarity(I2,T2,dim=0)
                    # tau 값을 넣으면 너무 커져서 안됨 .. batch size에 따라서 조절해야할듯..        
            anisotropy[i] = anisotropyj/self.batch_size#*tau
        return anisotropy
    
    def Total_loss(self):
        alignment  = self.Alignment()
        anisotropy = self.Anisotropy()
        return torch.sum(alignment+anisotropy)

h1 = torch.randn(64,152)
h2 = torch.randn(64,152)
total_loss = SimLoss(h1,h2,h1,h2)
total_loss.Alignment().shape
total_loss.Total_loss()
# torch.sum(total_loss.Alignment()+total_loss.Anisotropy())

tensor(0.0023)

In [120]:
round(total_loss.Total_loss().item(),7)

0.0023465

In [1]:
from transformers import CLIPProcessor, CLIPModel,AutoProcessor, AutoTokenizer

processor = AutoProcessor.from_pretrained("Soran/youtube_CLIP_LoRA_SimCSE_newloss2")
tokenizer = AutoTokenizer.from_pretrained("Soran/youtube_CLIP_LoRA_SimCSE_newloss2")

# model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
model = CLIPModel.from_pretrained("Soran/youtube_CLIP_LoRA_SimCSE_newloss2")

# REPO_NAME = "youtube_CLIP_LoRA_SimCSE_newloss3"
# AUTH_TOKEN = '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'
# model.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )

# tokenizer.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )

# processor.push_to_hub(
#     REPO_NAME, 
#     use_temp_dir=True, 
#     use_auth_token=AUTH_TOKEN
# )




Some weights of the model checkpoint at Soran/youtube_CLIP_LoRA_SimCSE_newloss2 were not used when initializing CLIPModel: ['text_model.encoder.layers.6.self_attn.k_proj.lora_A.default.weight', 'vision_model.encoder.layers.8.self_attn.k_proj.lora_A.default.weight', 'text_model.encoder.layers.6.self_attn.out_proj.lora_B.default.weight', 'vision_model.encoder.layers.6.self_attn.q_proj.lora_A.default.weight', 'vision_model.encoder.layers.11.self_attn.v_proj.lora_B.default.weight', 'text_model.encoder.layers.4.self_attn.out_proj.lora_A.default.weight', 'vision_model.encoder.layers.6.self_attn.q_proj.lora_B.default.weight', 'text_model.encoder.layers.0.self_attn.out_proj.lora_A.default.weight', 'text_model.encoder.layers.2.self_attn.v_proj.lora_B.default.weight', 'text_model.encoder.layers.0.self_attn.v_proj.lora_A.default.weight', 'text_model.encoder.layers.7.self_attn.q_proj.lora_B.default.weight', 'vision_model.encoder.layers.7.self_attn.out_proj.lora_A.default.weight', 'vision_model.enc

In [4]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities
probs

tensor([[0.9949, 0.0051]], grad_fn=<SoftmaxBackward0>)